// <auto-generated />
namespace PAngeda_Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Complet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Complet));
        
        string IMigrationMetadata.Id
        {
            get { return "202210110515113_Complet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
